=== konaindev/React-Django/data/schema/jsonschema/ImportedModelingData.schema.json
{
    "$ref": "#/definitions/ImportedModelingData",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "AcquisitionCategories<number>": {
            "description": "Acquisition funnel categories",
            "properties": {
                "app": {
                    "description": "Lease applications",
                    "type": "number"
                },
                "exe": {
                    "description": "Lease executions",
                    "type": "number"
                },
                "inq": {
                    "description": "Inquiries",
                    "type": "number"
                },
                "tou": {
                    "description": "Tours",
                    "type": "number"
                },
                "usv": {
                    "description": "Unique site visitors",
                    "type": "number"
                }
            },
            "required": [
                "app",
                "exe",
                "inq",
                "tou",
                "usv"
            ],
            "type": "object"
        },
        "AcquisitionCategories<string>": {
            "description": "Acquisition funnel categories",
            "properties": {
                "app": {
                    "description": "Lease applications",
                    "type": "string"
                },
                "exe": {
                    "description": "Lease executions",
                    "type": "string"
                },
                "inq": {
                    "description": "Inquiries",
                    "type": "string"
                },
                "tou": {
                    "description": "Tours",
                    "type": "string"
                },
                "usv": {
                    "description": "Unique site visitors",
                    "type": "string"
                }
            },
            "required": [
                "app",
                "exe",
                "inq",
                "tou",
                "usv"
            ],
            "type": "object"
        },
        "AcquisitionConversions<number>": {
            "description": "Acquisition conversions",
            "properties": {
                "app_exe": {
                    "description": "APP > EXE conversion rate @computed",
                    "type": "number"
                },
                "inq_tou": {
                    "description": "INQ > TOU conversion rate @computed",
                    "type": "number"
                },
                "tou_app": {
                    "description": "TOU > APP conversion rate @computed",
                    "type": "number"
                },
                "usv_exe": {
                    "description": "USV > EXE conversion rate @computed",
                    "type": "number"
                },
                "usv_inq": {
                    "description": "USV > INQ conversion rate @computed",
                    "type": "number"
                }
            },
            "required": [
                "app_exe",
                "inq_tou",
                "tou_app",
                "usv_exe",
                "usv_inq"
            ],
            "type": "object"
        },
        "AcquisitionFunnel": {
            "description": "Acquisition funnel",
            "properties": {
                "conversions": {
                    "$ref": "#/definitions/AcquisitionConversions<number>",
                    "description": "Conversion rates in the acquisition funnel @computed"
                },
                "costs": {
                    "$ref": "#/definitions/AcquisitionCategories<string>",
                    "description": "Cost-pers in the acquisition funnel @computed"
                },
                "volumes": {
                    "$ref": "#/definitions/AcquisitionCategories<number>",
                    "description": "Absolute volumes in the acquisition funnel"
                }
            },
            "required": [
                "conversions",
                "costs",
                "volumes"
            ],
            "type": "object"
        },
        "ImportedModelingData": {
            "properties": {
                "dates": {
                    "$ref": "#/definitions/TimeSpan",
                    "description": "Dates for the report"
                },
                "four_week_funnel_averages": {
                    "$ref": "#/definitions/AcquisitionCategories<number>",
                    "description": "Four-week details for the acquisition funnel"
                },
                "funnel": {
                    "$ref": "#/definitions/AcquisitionFunnel",
                    "description": "The acqusition funnel"
                },
                "investment": {
                    "$ref": "#/definitions/Investment",
                    "description": "Investment expenses and outcomes, all categories"
                },
                "name": {
                    "description": "A description of this option, like \"Schedule Driven\"",
                    "type": "string"
                },
                "property": {
                    "$ref": "#/definitions/Property",
                    "description": "Property details for the report"
                },
                "targets": {
                    "items": {
                        "$ref": "#/definitions/ImportedModelingTargets"
                    },
                    "type": "array"
                }
            },
            "required": [
                "dates",
                "four_week_funnel_averages",
                "funnel",
                "investment",
                "name",
                "property",
                "targets"
            ],
            "type": "object"
        },
        "ImportedModelingTargets": {
            "properties": {
                "end": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                },
                "target_acq_expenses": {
                    "$ref": "#/definitions/InvestmentExpenses",
                    "description": "from individual AQC [sic] columns"
                },
                "target_acq_investment": {
                    "description": "summed from \"AQC [sic] Reputation Building, AQC Demand Creation, AQC Leasing Enablemenet, AQC Market Intelligence\" columns",
                    "type": "string"
                },
                "target_delta_leases": {
                    "description": "from \"Weekly Delta Leased Units\" column",
                    "type": "integer"
                },
                "target_inquiries": {
                    "description": "from \"INQs\" column",
                    "type": "integer"
                },
                "target_lease_applications": {
                    "description": "from \"Apps\" column",
                    "type": "integer"
                },
                "target_lease_cds": {
                    "description": "from \"C/D\" column",
                    "type": "integer"
                },
                "target_lease_renewal_notices": {
                    "description": "from \"Notice to Renew\" column",
                    "type": "integer"
                },
                "target_lease_renewals": {
                    "description": "from \"Renewals\" column",
                    "type": "integer"
                },
                "target_lease_vacation_notices": {
                    "description": "from \"Notice to Vacate\" column",
                    "type": "integer"
                },
                "target_leased_rate": {
                    "description": "from \"Lease Up %\" column",
                    "type": "number"
                },
                "target_leases_executed": {
                    "description": "from \"EXE\" column",
                    "type": "integer"
                },
                "target_move_ins": {
                    "description": "from \"Move Ins\" column",
                    "type": "integer"
                },
                "target_move_outs": {
                    "description": "from \"Move Outs\" column",
                    "type": "integer"
                },
                "target_occupied_units": {
                    "description": "from \"Occupied Units\" column",
                    "type": "integer"
                },
                "target_ret_expenses": {
                    "$ref": "#/definitions/InvestmentExpenses",
                    "description": "from individual Ret columns"
                },
                "target_ret_investment": {
                    "description": "summed from \"Ret Reputation Building, Ret Demand Creation, Ret Leasing Enablemenet, Ret Market Intelligence\" columns",
                    "type": "string"
                },
                "target_tours": {
                    "description": "from \"TOU\" column",
                    "type": "integer"
                },
                "target_usvs": {
                    "description": "from \"USVs\" column",
                    "type": "integer"
                }
            },
            "required": [
                "end",
                "start",
                "target_acq_expenses",
                "target_acq_investment",
                "target_delta_leases",
                "target_inquiries",
                "target_lease_applications",
                "target_lease_cds",
                "target_lease_renewal_notices",
                "target_lease_renewals",
                "target_lease_vacation_notices",
                "target_leased_rate",
                "target_leases_executed",
                "target_move_ins",
                "target_move_outs",
                "target_occupied_units",
                "target_ret_expenses",
                "target_ret_investment",
                "target_tours",
                "target_usvs"
            ],
            "type": "object"
        },
        "Investment": {
            "description": "All marketing investment categories",
            "properties": {
                "acquisition": {
                    "$ref": "#/definitions/InvestmentCategoryWithExpenses",
                    "description": "Investment and returns for the acquisition funnel"
                },
                "retention": {
                    "$ref": "#/definitions/InvestmentCategoryWithExpenses",
                    "description": "Investment and returns for the retention funnel"
                },
                "total": {
                    "$ref": "#/definitions/InvestmentCategory",
                    "description": "Total investment and returns across all funnels @computed"
                }
            },
            "required": [
                "acquisition",
                "retention",
                "total"
            ],
            "type": "object"
        },
        "InvestmentCategory": {
            "description": "Per-category investment breakdown",
            "properties": {
                "estimated_revenue_gain": {
                    "description": "The estimated revenue gain as a function of monthly rent @computed",
                    "type": "string"
                },
                "romi": {
                    "description": "The return on investment @computed",
                    "type": "integer"
                },
                "total": {
                    "description": "The total spent across all buckets @computed",
                    "type": "string"
                }
            },
            "required": [
                "estimated_revenue_gain",
                "romi",
                "total"
            ],
            "type": "object"
        },
        "InvestmentCategoryWithExpenses": {
            "properties": {
                "estimated_revenue_gain": {
                    "description": "The estimated revenue gain as a function of monthly rent @computed",
                    "type": "string"
                },
                "expenses": {
                    "$ref": "#/definitions/InvestmentExpenses",
                    "description": "Breakdown of marketing expenses into sub-buckets"
                },
                "romi": {
                    "description": "The return on investment @computed",
                    "type": "integer"
                },
                "total": {
                    "description": "The total spent across all buckets @computed",
                    "type": "string"
                }
            },
            "required": [
                "estimated_revenue_gain",
                "expenses",
                "romi",
                "total"
            ],
            "type": "object"
        },
        "InvestmentExpenses": {
            "description": "Marketing investment expense buckets",
            "properties": {
                "demand_creation": {
                    "type": "string"
                },
                "leasing_enablement": {
                    "type": "string"
                },
                "market_intelligence": {
                    "type": "string"
                },
                "reputation_building": {
                    "type": "string"
                }
            },
            "required": [
                "demand_creation",
                "leasing_enablement",
                "market_intelligence",
                "reputation_building"
            ],
            "type": "object"
        },
        "Leasing": {
            "description": "Leasing -- the \"logical\" side of renting",
            "properties": {
                "cd_rate": {
                    "description": "Cancellations/denials as percentage of lease application @computed",
                    "type": "number"
                },
                "cds": {
                    "description": "Number of cancellations AND denials",
                    "type": "integer"
                },
                "change": {
                    "description": "Net change in number of leases during this period @computed",
                    "type": "integer"
                },
                "rate": {
                    "description": "Lease rate as a function of occupiable units @computed",
                    "type": "number"
                },
                "renewal_notices": {
                    "description": "Number of new notices to renew",
                    "type": "integer"
                },
                "renewal_rate": {
                    "description": "Renewal rate @computed",
                    "type": "number"
                },
                "renewals": {
                    "description": "Number of renewals actually effected in timeframe",
                    "type": "integer"
                },
                "resident_decisions": {
                    "description": "Number of resident decisions (typically, due to expire leases)",
                    "type": "integer"
                },
                "units": {
                    "description": "Number of leased units at end of report period @computed",
                    "type": "integer"
                },
                "vacation_notices": {
                    "description": "Number of notices to vacate",
                    "type": "integer"
                }
            },
            "required": [
                "cd_rate",
                "cds",
                "change",
                "rate",
                "renewal_notices",
                "renewal_rate",
                "renewals",
                "resident_decisions",
                "units",
                "vacation_notices"
            ],
            "type": "object"
        },
        "Occupancy": {
            "description": "Occupancy -- the \"physical\" side of renting",
            "properties": {
                "move_ins": {
                    "description": "Number of units moved into during period",
                    "type": "integer"
                },
                "move_outs": {
                    "description": "Number of units moved out of during period",
                    "type": "integer"
                },
                "occupiable": {
                    "description": "Number of occupiable units at the end of report period",
                    "type": "integer"
                },
                "rate": {
                    "description": "Ratio of occupied to occupiable units @computed",
                    "type": "number"
                },
                "units": {
                    "description": "Number of occupied units at end of report period @computed",
                    "type": "integer"
                }
            },
            "required": [
                "move_ins",
                "move_outs",
                "occupiable",
                "rate",
                "units"
            ],
            "type": "object"
        },
        "Property": {
            "description": "Property-wide behavior",
            "properties": {
                "average_monthly_rent": {
                    "description": "The average rent, across all units, during this period",
                    "type": "string"
                },
                "cost_per_exe_vs_rent": {
                    "description": "The cost per exe vs the monthly average rent during this period",
                    "type": "number"
                },
                "leasing": {
                    "$ref": "#/definitions/Leasing",
                    "description": "Basic leasing information for the period"
                },
                "lowest_monthly_rent": {
                    "description": "The lowest rent, across all units, during this period",
                    "type": "string"
                },
                "occupancy": {
                    "$ref": "#/definitions/Occupancy",
                    "description": "Basic occupancy information for the period"
                },
                "total_units": {
                    "description": "The total number of units in this property during this period (older buildings may not specify)",
                    "type": [
                        "null",
                        "number"
                    ]
                }
            },
            "required": [
                "average_monthly_rent",
                "cost_per_exe_vs_rent",
                "leasing",
                "lowest_monthly_rent",
                "occupancy",
                "total_units"
            ],
            "type": "object"
        },
        "TimeSpan": {
            "description": "A date range. Start dates are inclusive; end dates are exclusive.",
            "properties": {
                "end": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                }
            },
            "required": [
                "end",
                "start"
            ],
            "type": "object"
        }
    }
}

=== konaindev/React-Django/data/examples/ImportedModelingData.json
{
  "name": "May Deadline - Conversion Focus",
  "dates": {
    "start": "2019-04-17",
    "end": "2019-05-28"
  },
  "property": {
    "average_monthly_rent": "1948.00",
    "lowest_monthly_rent": "1948.00",
    "cost_per_exe_vs_rent": 0.24373909137577002,
    "total_units": 199,
    "leasing": {
      "change": 46,
      "cds": 18,
      "cd_rate": 0.2727272727272727,
      "renewal_notices": 2,
      "renewals": 2,
      "renewal_rate": 0.5,
      "resident_decisions": 4,
      "vacation_notices": 2,
      "rate": 0.9698492462311558,
      "units": 193
    },
    "occupancy": {
      "move_ins": 24,
      "move_outs": 2,
      "rate": 0.964824120603015,
      "units": 192,
      "occupiable": 199
    }
  },
  "funnel": {
    "volumes": {
      "usv": 3180,
      "inq": 294,
      "tou": 108,
      "app": 66,
      "exe": 48
    },
    "costs": {
      "usv": "7.17",
      "inq": "77.52",
      "tou": "211.02",
      "app": "345.31",
      "exe": "474.80"
    },
    "conversions": {
      "usv_inq": 0.09245283018867924,
      "inq_tou": 0.3673469387755102,
      "tou_app": 0.6111111111111112,
      "app_exe": 0.7272727272727273,
      "usv_exe": 0.015094339622641511
    }
  },
  "four_week_funnel_averages": {
    "usv": 2120,
    "inq": 196,
    "tou": 72,
    "app": 44,
    "exe": 32
  },
  "investment": {
    "acquisition": {
      "expenses": {
        "demand_creation": "14300.56",
        "leasing_enablement": "6500.00",
        "market_intelligence": "1990.02",
        "reputation_building": "0.00"
      },
      "total": "22790.58",
      "romi": 25,
      "estimated_revenue_gain": "561024.00"
    },
    "retention": {
      "expenses": {
        "demand_creation": "0.00",
        "leasing_enablement": "4249.98",
        "market_intelligence": "1989.99",
        "reputation_building": "0.00"
      },
      "total": "6239.97",
      "romi": 7,
      "estimated_revenue_gain": "46752.00"
    },
    "total": {
      "total": "29030.55",
      "romi": 21,
      "estimated_revenue_gain": "607776.00"
    }
  },
  "targets": [
    {
      "start": "2019-04-17",
      "target_leased_rate": 0.7788944723618091,
      "target_lease_applications": 11,
      "target_leases_executed": 8,
      "target_lease_renewal_notices": 1,
      "target_lease_renewals": 0,
      "target_lease_vacation_notices": 1,
      "target_lease_cds": 3,
      "target_delta_leases": 8,
      "target_move_ins": 0,
      "target_move_outs": 0,
      "target_occupied_units": 154,
      "target_acq_expenses": {
        "demand_creation": "1666.76",
        "leasing_enablement": "0.00",
        "market_intelligence": "331.67",
        "reputation_building": "0.00"
      },
      "target_ret_expenses": {
        "demand_creation": "0.00",
        "leasing_enablement": "458.33",
        "market_intelligence": "331.67",
        "reputation_building": "0.00"
      },
      "target_usvs": 530,
      "target_inquiries": 49,
      "target_tours": 18,
      "end": "2019-04-24",
      "target_acq_investment": "1998.43",
      "target_ret_investment": "790.00"
    },
    {
      "start": "2019-04-24",
      "target_leased_rate": 0.8190954773869347,
      "target_lease_applications": 11,
      "target_leases_executed": 8,
      "target_lease_renewal_notices": 0,
      "target_lease_renewals": 1,
      "target_lease_vacation_notices": 1,
      "target_lease_cds": 3,
      "target_delta_leases": 8,
      "target_move_ins": 0,
      "target_move_outs": 0,
      "target_occupied_units": 162,
      "target_acq_expenses": {
        "demand_creation": "1666.76",
        "leasing_enablement": "0.00",
        "market_intelligence": "331.67",
        "reputation_building": "0.00"
      },
      "target_ret_expenses": {
        "demand_creation": "0.00",
        "leasing_enablement": "458.33",
        "market_intelligence": "331.67",
        "reputation_building": "0.00"
      },
      "target_usvs": 530,
      "target_inquiries": 49,
      "target_tours": 18,
      "end": "2019-05-01",
      "target_acq_investment": "1998.43",
      "target_ret_investment": "790.00"
    },
    {
      "start": "2019-05-01",
      "target_leased_rate": 0.8592964824120602,
      "target_lease_applications": 11,
      "target_leases_executed": 8,
      "target_lease_renewal_notices": 0,
      "target_lease_renewals": 0,
      "target_lease_vacation_notices": 0,
      "target_lease_cds": 3,
      "target_delta_leases": 8,
      "target_move_ins": 0,
      "target_move_outs": 0,
      "target_occupied_units": 170,
      "target_acq_expenses": {
        "demand_creation": "1666.76",
        "leasing_enablement": "0.00",
        "market_intelligence": "331.67",
        "reputation_building": "0.00"
      },
      "target_ret_expenses": {
        "demand_creation": "0.00",
        "leasing_enablement": "458.33",
        "market_intelligence": "331.67",
        "reputation_building": "0.00"
      },
      "target_usvs": 530,
      "target_inquiries": 49,
      "target_tours": 18,
      "end": "2019-05-08",
      "target_acq_investment": "1998.43",
      "target_ret_investment": "790.00"
    },
    {
      "start": "2019-05-08",
      "target_leased_rate": 0.8944723618090452,
      "target_lease_applications": 11,
      "target_leases_executed": 8,
      "target_lease_renewal_notices": 1,
      "target_lease_renewals": 1,
      "target_lease_vacation_notices": 0,
      "target_lease_cds": 3,
      "target_delta_leases": 7,
      "target_move_ins": 8,
      "target_move_outs": 1,
      "target_occupied_units": 177,
      "target_acq_expenses": {
        "demand_creation": "1666.76",
        "leasing_enablement": "0.00",
        "market_intelligence": "331.67",
        "reputation_building": "0.00"
      },
      "target_ret_expenses": {
        "demand_creation": "0.00",
        "leasing_enablement": "458.33",
        "market_intelligence": "331.67",
        "reputation_building": "0.00"
      },
      "target_usvs": 530,
      "target_inquiries": 49,
      "target_tours": 18,
      "end": "2019-05-15",
      "target_acq_investment": "1998.43",
      "target_ret_investment": "790.00"
    },
    {
      "start": "2019-05-15",
      "target_leased_rate": 0.9296482412060302,
      "target_lease_applications": 11,
      "target_leases_executed": 8,
      "target_lease_renewal_notices": 0,
      "target_lease_renewals": 0,
      "target_lease_vacation_notices": 0,
      "target_lease_cds": 3,
      "target_delta_leases": 7,
      "target_move_ins": 8,
      "target_move_outs": 1,
      "target_occupied_units": 184,
      "target_acq_expenses": {
        "demand_creation": "1666.76",
        "leasing_enablement": "0.00",
        "market_intelligence": "331.67",
        "reputation_building": "0.00"
      },
      "target_ret_expenses": {
        "demand_creation": "0.00",
        "leasing_enablement": "458.33",
        "market_intelligence": "331.67",
        "reputation_building": "0.00"
      },
      "target_usvs": 530,
      "target_inquiries": 49,
      "target_tours": 18,
      "end": "2019-05-22",
      "target_acq_investment": "1998.43",
      "target_ret_investment": "790.00"
    },
    {
      "start": "2019-05-22",
      "target_leased_rate": 0.9698492462311558,
      "target_lease_applications": 11,
      "target_leases_executed": 8,
      "target_lease_renewal_notices": 0,
      "target_lease_renewals": 0,
      "target_lease_vacation_notices": 0,
      "target_lease_cds": 3,
      "target_delta_leases": 8,
      "target_move_ins": 8,
      "target_move_outs": 0,
      "target_occupied_units": 192,
      "target_acq_expenses": {
        "demand_creation": "1666.76",
        "leasing_enablement": "0.00",
        "market_intelligence": "331.67",
        "reputation_building": "0.00"
      },
      "target_ret_expenses": {
        "demand_creation": "0.00",
        "leasing_enablement": "458.33",
        "market_intelligence": "331.67",
        "reputation_building": "0.00"
      },
      "target_usvs": 530,
      "target_inquiries": 49,
      "target_tours": 18,
      "end": "2019-05-29",
      "target_acq_investment": "1998.43",
      "target_ret_investment": "790.00"
    }
  ]
}
